//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsCampaign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignBookedInfo
    {
        public int id { get; set; }
        public string PlayerName { get; set; }
        public string PlayerAge { get; set; }
        public int campaignID { get; set; }
        public string ContactNumber { get; set; }
        public int catagoryID { get; set; }
        public string MedicalCondition { get; set; }
    
        public virtual CampaignTable CampaignTable { get; set; }
        public virtual catagoryTable catagoryTable { get; set; }
    }
}
