//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsCampaign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactTable
    {
        public int id { get; set; }
        public string senderName { get; set; }
        public string senderEmail { get; set; }
        public string senderMessage { get; set; }
    }
}
