//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsCampaign.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class RegisterTable
    {
        public int id { get; set; }
        [Required(ErrorMessage="First Name required...")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "Last Name required...")]
        public string lastName { get; set; }
        [Required(ErrorMessage = "Email required...")]
        [EmailAddress(ErrorMessage="Give the right formate")]
        public string email { get; set; }
        [Required(ErrorMessage = "User Name required...")]
        [Remote("IsUserNameExists","Sports",ErrorMessage="User name already exist!!!")]
        public string userName { get; set; }
        [Required(ErrorMessage = "Password required...")]
        public string userPassword { get; set; }
    }
}
